---
title: "Expected numbers of full and half-sibling pairs between surveys"
author: "Robin Aldridge-Sutton"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Full-sibling pairs

## Younger animal alive at time of first sample

$$ 2 E(FSP_{t_1}) \phi^{t_2 - t_1} $$

### Younger animal born between sample-times

If an animal $j$ is born at a time $b_2$ such that $t_1 < b_2 \le t_2$, then there is an FSP between $t_1$ and $t_2$ for each animal $i$ that is born at a time $b_1$ before $t_1$, so that $b_1 < t_1$, and survives until $t_1$, and has a mother that survives until $b_2$, and gives birth to $j$ then, and a father that survives to $b_2 - 1$ and conceives $j$ then, given $j$ survives to $t_2$.

The probability that $i$ survives to $t_1$ is $\phi^{t_1 - b_1}$.

The probability that the mother survives from $b_1$ to $b_2$ is $\phi^{b_2 - b_1}$.

The probability that the mother has another calf at $b_2$, given that she survives until then, is $\beta$.

The probability that the father survives from $b_1 - 1$ to $b_2 - 1$ is $\phi^{b_2 - 1 - (b_1 - 1)} = \phi^{b_2 - b_1}$.

The probability that the father conceives a calf at $b_2 - 1$, given that he survives until then, is $\frac{1}{M^*_{b_2-1}}$.

The probability that this calf survives to time $t_2$ is $\phi^{t_2 - b_2}$.

For each animal born at time $b_1$ the probability that it forms a pair such as $i$ and $j$ is then 
$$\phi^{t_1 - b_1} \phi^{b_2 - b_1} \beta \phi^{b_2 - b_1} \frac{1}{M^*_{b_2-1}} \phi^{t_2 - b_2} = \frac{\beta \phi^{t_1 + t_2 + b_2 - 3 b_1}}{M^*_{b_2-1}}.$$

Let $FSP_{t_1, t_2, b_1, b_2}$ be the number of pairs such as $i$ and $j$.  Then
$$FSP_{t_1, t_2, b_1, b_2} \sim Bin \left( B_{b_1}, \frac{\beta \phi^{t_1 + t_2 + b_2 - 3 b_1}}{M^*_{b_2-1}} \right),$$
and following the same reasoning as above
$$E(FSP_{t_1, t_2, b_1, b_2}) = E(B_{b_1}) \frac{\beta \phi^{t_1 + t_2 + b_2 - 3 b_1}}{M^*_{b_2-1}}$$
$$= E(N_{b_1}) \left(1 - \frac{\phi}{\lambda}\right) \frac{\beta \phi^{t_1 + t_2 + b_2 - 3 b_1}}{M^*_{b_2-1}}$$
...
$$$$

Let 

- $FSP_{t, b_1, b_2, i}$ be the number of pairs of animals at time $t$, that include a particular animal $i$, that is born at time $b_1$, and an animal born at a later time $b_2$, that has the same mother and the same father (full-sibling pairs), and 
- $FSP_{t, b_1, b_2}$ be the total number of pairs at time $t$ that include any animal born at time $b_1$, and an animal born at a later time $b_2$, that has the same mother and the same father.

Then following the logic as the cases for same-mother and same-father pairs we have that the probability that an animal born at time $b_1$ survives to time $t$ and an animal born at time $b_2$ forms a full-sibling pair with it at time $t$ is $\frac{\phi^{2(t - b_1)}}{M^*_{b_2 - 1}F_{b_2}}$.  Also following the logic through (I need to explain this properly) we find that
$$E(FSP_{t, b_1, b_2}) = \frac{E(SFP_{t, b_1, b_2}) \phi^{b_2 - b_1}}{E(F_{b_2})}$$
$$= \frac{E(SMP_{t, b_1, b_2}) \phi^{b_2 - b_1 + 1}}{E(F_{b_2})}$$
$$= \frac{E(N_t)\beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \phi^{b_2 - b_1 + 1}}{\frac{E(N_{b_2})}{2}\left(\frac{\phi}{\lambda}\right)^\alpha}$$
$$= E(N_t)\beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \phi^{b_2 - b_1 + 1} \frac{2}{E(N_{b_2})}\left(\frac{\lambda}{\phi}\right)^\alpha$$
$$= E(N_t)\beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \phi^{b_2 - b_1 + 1} \frac{2 \lambda^{t - b_2}}{E(N_t)} \left(\frac{\lambda}{\phi}\right)^\alpha$$
$$= 2 \beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\lambda}{\phi}\right)^\alpha \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \phi^{b_2 - b_1 + 1} \lambda^{t - b_2}$$

$$E(FSP_{t}) = \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}E(FSP_{t, b_1, b_2})$$
$$= \sum_{b_1 < t}\sum_{b_1 < b_2 \le t} 2 \beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\lambda}{\phi}\right)^\alpha \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \phi^{b_2 - b_1 + 1} \lambda^{t - b_2}$$
$$= 2 \beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\lambda}{\phi}\right)^\alpha \phi \sum_{b_1 < t} \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \sum_{b_1 < b_2 \le t} \phi^{b_2 - b_1} \lambda^{t - b_2},$$
$$\sum_{b_1 < t} \left(\frac{\phi^2}{\lambda}\right)^{t - b_1} \sum_{b_1 < b_2 \le t} \phi^{b_2 - b_1} \lambda^{t - b_2} = \frac{\phi^2}{\lambda}\phi + \left(\frac{\phi^2}{\lambda}\right)^2 (\phi^2 + \phi \lambda) + \left(\frac{\phi^2}{\lambda}\right)^3 (\phi^3 + \phi^2\lambda + \phi\lambda^2) + ...$$
$$= \frac{1}{1 - \frac{\phi^2}{\lambda}\phi} \left\{ \frac{\phi^2}{\lambda}\phi + \left(\frac{\phi^2}{\lambda}\right)^2 (\phi^2 + \phi \lambda) + \left(\frac{\phi^2}{\lambda}\right)^3 (\phi^3 + \phi^2\lambda + \phi\lambda^2) + ... \\ - \left(\frac{\phi^2}{\lambda}\right)^2 \phi^2 - \left(\frac{\phi^2}{\lambda}\right)^3 (\phi^3 + \phi^2\lambda) - ... \right\}$$
$$= \frac{1}{1 - \frac{\phi^2}{\lambda}\phi} \left\{ \frac{\phi^2}{\lambda}\phi + \left(\frac{\phi^2}{\lambda}\right)^2 \phi\lambda + \left(\frac{\phi^2}{\lambda}\right)^3 \phi\lambda^2 + .... \right\}$$
$$= \frac{\phi}{1 - \frac{\phi^3}{\lambda}} \left\{ \frac{\phi^2}{\lambda} + \left(\frac{\phi^2}{\lambda}\right)^2 \lambda + \left(\frac{\phi^2}{\lambda}\right)^3 \lambda^2 + .... \right\}$$

$$= \frac{\phi\lambda}{\lambda - \phi^3} \left\{ \frac{\phi^2}{\lambda} + \frac{\phi^4}{\lambda} + \frac{\phi^6}{\lambda} + ... \right\}$$
$$= \frac{\phi}{\lambda - \phi^3} \left\{\phi^2 + \phi^4 + \phi^6 + ... \right\}$$
$$= \frac{\phi}{\lambda - \phi^3} \frac{\phi^2}{1 - \phi^2}$$
$$= \frac{\phi^3}{(\lambda - \phi^3)(1 - \phi^2)},$$
$$E(FSP_{t}) = 2 \beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\lambda}{\phi}\right)^\alpha \phi \frac{\phi^3}{(\lambda - \phi^3)(1 - \phi^2)}$$
$$= 2 \beta \left(1 - \frac{\phi}{\lambda}\right) \left(\frac{\lambda}{\phi}\right)^\alpha \frac{\phi^4}{(\lambda - \phi^3)(1 - \phi^2)}$$
$$= 2 \beta \left(\frac{\lambda}{\phi}\right)^\alpha \frac{(\lambda - \phi) \phi^4}{\lambda (\lambda - \phi^3)(1 - \phi^2)}$$

### Half-sibling pairs

Let $HSP_t$ be the number of half-sibling pairs at time $t$.  Then
$$HSP_t = SMP_t + SFP_t - 2 FSP_t,$$
and
$$E(HSP_t) = E(SMP_t + SFP_t - 2 FSP_t)$$
$$= E(SMP_t) + E(SFP_t) - 2 E(FSP_t)$$
The half-sibling pair *probability* is then found by dividing the expected number of half-sibling pairs by the expected total number of pairs, which we approximate with
$$\frac{E(N_t) \left\{E(N_t - 1) \right\}}{2}.$$

**End of current work**

The same process leads to the probability for pairs between samples at times $t_1$ and $t_2$, where $t_1 < t_2$, by simply replacing $t$ with $t_1$ in the first sum, as the older sibling must be born before the first sample, and replacing $t$ with $t_2$ in the second sum, as the younger sibling can be born anytime before the second sample.  The sums may not simplify as nicely then though.  I haven't tried this yet.