---
title: "Notes on mother-offspring probability from close-kin mark-recapture (2016)"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float: true
---

Bravington, Mark V., Hans J. Skaug, and Eric C. Anderson. "Close-kin mark-recapture." Statistical Science 31.2 (2016): 259-274.

# Kinship probabilities

## Kinship probability for mother-offspring as expected relative reproductive output

Let

- $i$ be a female
- $j$ be an offspring
- $K_{i j}$ be the event that $i$ is the mother of $j$
- $x_j$ and $y_j$ be the place and time of $j$'s birth
- $R_i(x_j, y_j)$ be the reproductive output of $i$ at $(x_j, y_j)$, and
- $R_+(x_j, y_j)$ be the reproductive output of all adult females at $(x_j, y_j)$.
- $z_.$ be the covariate vector of an individual $.$, 
  - all the information about $.$, except its genotype and kinship to other individuals, that is recorded when it is captured, 
  - viewed stochastically,

Assume that

- all offspring with the same $(x, y)$ have equal survival and sampling probabilities.

Then

$$\mathbb{P}[K_{i j} = MO|R_i, R_+, z_i, z_j] = \mathbb{P}[K_{i j} = MO|R_i, R_+] = \frac{R_i(x_j, y_j)}{R_+(x_j, y_j)}$$
and
\begin{equation}
  \mathbb{P}[K_{i j} = MO|z_i, z_j] = \mathbb{E}_{X_j, Y_j|z_j} \left[\frac{\mathbb{E}[R_i(X_j, Y_j)|z_i]} {\mathbb{E}[R_+(X_j, Y_j)]} \right].
  (\#eq:PMO)
\end{equation}

### Robin's note

$$\mathbb{P}[K_{i j} = MO] = \mathbb{E}_{R_i, R_+} \left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)]}\right]$$
$$= \mathbb{E}_{R_i, R_+, X_j, Y_j} \left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)]}\right],$$
and
$$\mathbb{P}[K_{i j} = MO|z_i, z_j] = \mathbb{E}_{R_i, R_+, X_j, Y_j | z_i, z_j} \left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)}\right]$$
$$= \mathbb{E}_{X_j, Y_j|z_i, z_j} \left[\mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i, z_j}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)}\right]\right]$$
$$= \mathbb{E}_{X_j, Y_j|z_i, z_j} \left[\mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)}\right]\right],$$
assuming that $R_i$ and $R_+$ are conditionally independent of $z_j$ given $X_j$ and $Y_j$, i.e. that the covariates of offspring $j$ do not inform the distribution of reproductive output at the place and time of their birth except through the distributions of that place and that time,
$$= \mathbb{E}_{X_j, Y_j|z_j} \left[\mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)}\right]\right],$$
assuming that $X_j$ and $Y_j$ are independent of $z_i$, i.e. that the covariates of the female $i$ do not inform the distribution of the place and time of offspring $j$'s birth.

\@ref(eq:PMO) also seems to require that
\begin{equation}
  \mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)}\right] = \frac{\mathbb{E}_{R_i | X_j, Y_j, z_i}[R_i(X_j, Y_j)]} {\mathbb{E}_{R_+ | X_j, Y_j, z_i}[R_+(X_j, Y_j)]},
  (\#eq:expratio)
\end{equation}
which would be true if $R_i$ and $R_+$ were independent given the place and time $(X_j, Y_j)$ of offspring $j$'s birth, and female $i$'s covariates $z_i$.  $R_+$ is a sum which includes $R_i$, and they are also likely to be influenced by common latent variables, for example food abundance, but \@ref(eq:expratio) is true given certain assumptions.

Let

- $\theta$ be the set of latent variables that influence both $R_i$ and $R_+$.

Then
$$\mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i}\left[ \frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)} \right] = \mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i, \theta}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)} \right] \right].$$

Let

- $N_{F}$ be the number of mature females at the place and time $(X_j, Y_j)$ of offspring $j$'s birth, 
- $R_k(X_j, Y_j)$ for $k = 1, ..., N_F$ be the reproductive output of each mature female at the place and time $(X_j, Y_j)$ of offspring $j$'s birth, and
- $M_i$ be the event that female $i$ was mature at time $Y_j$.

Assume that 

- $R_k(X_j, Y_j)$ for $k = 1, ..., N_F$ are i.i.d. given $\theta$ and female $i$'s covariates $z_i$ (this is unlikely, due to competition between individuals, but may still be a reasonable approximation).

Then 

$$\mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i, \theta}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)} \right] = \mathbb{E}_{R_1, ..., R_{N_F} | X_j, Y_j, z_i, \theta, N_F}\left[\frac{R_1(X_j, Y_j)} {\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \right] \mathbb{P}(M_i | X_j, Y_j, z_i)$$
$$\mathbb{E}_{R_1, ..., R_{N_F} | X_j, Y_j, z_i, \theta, N_F}\left[\frac{R_1(X_j, Y_j)} {\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \right] = \mathbb{E}_{\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \left[ \mathbb{E}_{R_1, ..., R_{N_F} | X_j, Y_j, z_i, \theta, N_F, \sum_{k = 1}^{N_F} R_k(X_j, Y_j)}\left[\frac{R_1(X_j, Y_j)} {\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \right] \right]$$
$$= \mathbb{E}_{\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \left[ \frac{1}{N_F} \mathbb{E}_{R_1, ..., R_{N_F} | X_j, Y_j, z_i, \theta, N_F, \sum_{k = 1}^{N_F} R_k(X_j, Y_j)}\left[\frac{\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} {\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \right] \right],$$
by symmetry,
$$= \mathbb{E}_{\sum_{k = 1}^{N_F} R_k(X_j, Y_j)} \left[ \frac{1}{N_F} \right]$$
$$= \frac{1} {N_F},$$
$$\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_i, R_+ | X_j, Y_j, z_i, \theta}\left[\frac{R_i(X_j, Y_j)} {R_+(X_j, Y_j)} \right] \right] = \mathbb{E}_{\theta | X_j, Y_j, z_i} \left[ \frac{1} {N_F} \mathbb{P}(M_i | X_j, Y_j, z_i) \right]$$
$$ = \frac{1} {N_F} \mathbb{P}(M_i | X_j, Y_j, z_i)$$

$$= \frac{\mathbb{P}(M_i | X_j, Y_j, z_i) \mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_1 | X_j, Y_j, z_i, \theta}[R_1(X_j, Y_j)] \right]} {N_F \mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_i | X_j, Y_j, z_i, \theta}[R_i(X_j, Y_j)] \right]}$$
$$= \frac{\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{P}(M_i | X_j, Y_j, z_i) \mathbb{E}_{R_1 | X_j, Y_j, z_i, \theta}[R_1(X_j, Y_j)] \right]} {\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ N_F \mathbb{E}_{R_i | X_j, Y_j, z_i, \theta}[R_i(X_j, Y_j)] \right]}$$
$$= \frac{\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_i | X_j, Y_j, z_i, \theta}[R_i(X_j, Y_j)] \right]} {\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_1, ..., R_{N_F} | X_j, Y_j, z_i, \theta, N_F}\left[ \sum_{k = 1}^{N_F} R_k(X_j, Y_j) \right] \right]}$$
$$= \frac{\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_i | X_j, Y_j, z_i, \theta}[R_i(X_j, Y_j)] \right]} {\mathbb{E}_{\theta | X_j, Y_j, z_i}\left[ \mathbb{E}_{R_+ | X_j, Y_j, z_i, \theta}[R_+(X_j, Y_j)] \right]}$$
\begin{equation}
  = \frac{\mathbb{E}_{R_i | X_j, Y_j, z_i}[R_i(X_j, Y_j)]} {\mathbb{E}_{R_+ | X_j, Y_j, z_i}[R_+(X_j, Y_j)]},
  (\#eq:expratio)
\end{equation}

\begin{equation}
  \mathbb{E}_{X_j, Y_j|z_j} \left[\frac{\mathbb{E}_{R_i | X_j, Y_j, z_i}[R_i(X_j, Y_j)]} {\mathbb{E}_{R_+ | X_j, Y_j, z_i}[R_+(X_j, Y_j)]}\right] = \mathbb{E}_{X_j, Y_j|z_j} \left[\frac{\mathbb{E}_{R_i | X_j, Y_j, z_i}[R_i(X_j, Y_j)]} {\mathbb{E}_{R_+ | X_j, Y_j}[R_+(X_j, Y_j)]}\right],
  (\#eq:indepzi)
\end{equation}
assuming that $R_+$ is conditionally independent of $z_i$ given $X_j$ and $Y_j$, i.e. that the covariates of female $i$ do not inform the distribution of reproductive output at the place and time of offspring $j$'s birth except through the distributions of that place and that time, and

\begin{equation}
  = \mathbb{E}_{X_j, Y_j|z_j} \left[\frac{\mathbb{E}[R_i(X_j, Y_j)|z_i]} {\mathbb{E}[R_+(X_j, Y_j)]}\right],
  (\#eq:PMO)
\end{equation}
making the other details of the inner expectations implicit.

## Base case: Ages known, constant fecundity, lethal sampling, no (spatial) stock structure

Let 

- $a$ be age
- $t$ be the time of capture
- $z = (t, a)$
- $\alpha$ be age-at-maturity
- $\mathbb{I}[.]$ be the indicator function, and
- $N_{F y_j}$ be the number of mature females at time $y_j$.

Assume that

- an adult's sampling and the number of its offspring sampled are independent given covariates, or more formally
  - there are no additional covariates that affect both the probability of an adult being sampled ($p$) and its expected reproductive output $(\mathbb{E}[R_{ij}])$, and
  - there are no additional covariates that affect the sampling and/or survival probabilities of both the adult and its offspring (e.g. *mother-calf pairs being caught together*).

Then 

- $y = t - a$
- given that $i$ was mature, and not yet lethally sampled, at $y_j$ she is just as likely to be $j$'s mother as the other mature females at that time due to constant fecundity, and

\begin{equation}
  \mathbb{P}[K_{i j} = MO|z_i, z_j] = \frac{\mathbb{E}[R_i(y_j)|y_i, t_i]} {\mathbb{E}[R_+(y_j)]}
  (\#eq:expratioconst)
\end{equation}

\begin{equation}
  = \frac{\mathbb{I}[y_i + \alpha \le y_j < t_i]} {N_{F y_j}}
  (\#eq:PMOconst)
\end{equation}

### Robin's note

- Fecundity is referred to elsewhere as $\beta := \mathbb{E}[R]$, but in this section they state that it is not required that all adults have the same expected reproductive output
- I am not sure whether constant $\beta := \mathbb{E}[R]$ implies \@ref(eq:expratio), but it does imply the inference from \@ref(eq:expratioconst) to \@ref(eq:PMOconst)
- Assuming that $R_k$ for $k = 1$ to $N_F$ are i.i.d. given all common latent variables $\theta$ does imply \@ref(eq:expratio), but also implies constant $\beta := \mathbb{E}[R]$ 
- So I am not sure what they mean by constant fecundity here
- There might be some connections between their assumptions in this section and those in my note above, but I am not sure

## Non-lethal sampling

$$\mathbb{P}[K_{i j} = MO|z_i, z_j] = \frac{\mathbb{I}[y_i + \alpha \le y_j]} {N_{F y_j}} \times
\begin{cases} 
  1; & t_i > y_j, \\
  \phi(t_i, y_j); & t_i < y_j,
\end{cases}$$
where $\phi(t_i, y_j)$ is the probability that $i$ survives from $t_i$ to $y_j$.

## Age-dependent sampling and fecundity, ages unknown

Let

- $p(a)$ be age-dependent sampling probability, and
- $\beta(a)$ be age-dependent fecundity.

Then \@ref(eq:PMOconst) becomes

$$\mathbb{P}[K_{i j} = MO|z_i, z_j] = \frac{\mathbb{I}[y_j < t_i] \times \beta(a_i - (t_i - y_j))} {\sum_{a \ge \alpha} \beta(a) N_{F a y_j}}.$$

Assume that 

- $a_i$ is unknown.

Then

$$\mathbb{P}[K_{i j} = MO|z_i, z_j] = \frac{\mathbb{I}[y_j < t_i] } {\sum_{a \ge \alpha} \beta(a) N_{F a y_j}}  \times \frac{\sum_{a > 0} \{ p(a) N_{F a t_i} \beta(a_i - (t_i - y_j)) \}} {\sum_{a > 0} p(a) N_{F a t_i}}.$$

Note

- They use $N_{F a t_j}$ in this formula but I think it must be a typo.

If $a_j$ is also unknown another summation is required with $p(a)$.  *They did a blue whale design study with non-lethal variants of this case, and $p(a)$ and $\beta(a)$ constant for $a > \alpha$ and zero otherwise, and simple deterministic demography giving closed form expressions for the sums.*  There is no reference here but there is Antarctic Blue Whale surveys: augmenting via genetics for close-kin and ordinal age Mark V. Bravington, Simon N. Jarman, Hans J. Skaug online.  It sounds like ours is similar but with more complicated non-deterministic demography.

### Robin's note

In our case we have non-lethal sampling, and assume i.i.d. $R_k$'s(?) and constant sampling probability, but we have ages unknown. Then

$$\mathbb{P}[K_{i j} = MO|z_i, z_j] = \sum_{a_i \ge \alpha} \mathbb{P}(A_i = a_i) \sum_{a_j > 0} \mathbb{P}(A_j = a_j) \times$$
$$\frac{\mathbb{I}[t_i - a_i + \alpha \le t_j - a_j]} {N_{F a_i (t_j - a_j)}} \times
\begin{cases} 
  1; & t_i > t_j - a_j, \\
  \phi(t_i, t_j - a_j); & t_i < t_j - a_j,
\end{cases}$$
where we sum over the possible ages of female $i$ and offspring $j$, weighted by their probabilities, checking that $i$ is mature when $j$ is born, and taking into account the probability that $i$ survives between then and being sampled.

But we derive it quite differently, by finding the expected number of mother-offspring pairs and dividing by an approximation for the expected total number of pairs, to approximate the undirected probability.  It would be good to try to derive it their way and compare the results.

It seems that they also ignore the demographics of the population in their models, or maybe just in these examples...  Maybe that's why they ignore the expectation problem I go into above.
