---
title: "Expected number of same-mother pairs"
author: "Robin Aldridge-Sutton"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Expected number of animals born at time $t$

Let 

- $N_t$ be a random variable representing the size of a given population at time $t$, and
- $\lambda := \frac {E(N_{t + 1})}{E(N_{t})}$ be the (constant) population growth rate, where $E(.)$ is the expected value of $.$.

Then
$$E(N_{t + 1}) = E(N_t) \lambda,$$
$$E(N_{t + 2}) = E(N_{t + 1}) \lambda = E(N_t) \lambda^2,$$
and
\begin{equation}
  E(N_{t_2}) = E(N_{t_1}) \lambda^{t_2 - t_1}.
  (\#eq:expNt)
\end{equation}

Let

- $A_t$ be the event that a given animal is alive in the population at time $t$,
- $\phi := P(A_{t + 1}|A_t)$ be the (constant) individual survival rate of all such animals, and
- $S_t$ be the number of animals that survive from time $t$ to time $t + 1$. 

Assume that

- the survival of each animal occurs independently of that of any other.

Then
$$S_t \sim Bin(N_{t}, \phi),$$
and
$$E(S_t) = E\{E(S_t|N_t)\}$$
$$= E(N_t \phi)$$
\begin{equation}
  E(S_t) = E(N_t) \phi.
  (\#eq:expSt)
\end{equation}

Let 

- $B_t$ be the number of animals that are born at time $t$.  

Assume that

- there is no migration to or from the population.

Then
$$B_t = N_t - S_{t - 1},$$
and
$$E(B_t) = E(N_t - S_{t - 1})$$
$$= E(N_t) - E(S_{t - 1})$$
$$= E(N_{t - 1}) \lambda - E(N_{t - 1}) \phi,$$
from \@ref(eq:expNt) and \@ref(eq:expSt),
\begin{equation}
  E(B_t) = E(N_{t - 1}) (\lambda - \phi).
  (\#eq:expBt)
\end{equation}

# Birth rate among mature females

Assume that 

- survival satisfies the Markov property $P(A_{t + 1}|A_t) = P(A_{t + 1}|A_t, A_{t - 1}, ...)$, i.e. survival at later times is independent of survival at earlier times.

Then
$$P(A_{t + 2}|A_t) = P(A_{t + 2}|A_{t + 1}, A_t) P(A_{t + 1}|A_t)$$
$$ = P(A_{t + 2}|A_{t + 1}) P(A_{t + 1}|A_t)$$
$$ = \phi^2,$$
and
\begin{equation}
  P(A_{t_2}|A_{t_1}) = \phi^{t_2 - t_1},
  (\#eq:phi)
\end{equation}
where $t_2 > t_1$.

Let 

- $\alpha$ be the age of sexual maturity of animals in the population, i.e. the minimum age at which an animal may have offspring alive in the population, and
- $F_t$ be the number of mature females that are alive in the population at time $t$.

Assume that

- animals are equally likely to be born male or female.

Then 

- an animal is alive and mature at time $t$ if and only if it was alive in the population at time $t - \alpha$ and survived to time $t$,
- the probability that an animal that was alive in the population at time $t - \alpha$ survives until time $t$ is 

$$P(A_{t}|A_{t - \alpha}) = \phi^{t - (t - \alpha)} = \phi^{\alpha},$$
from \@ref(eq:phi),

- the probability that an animal is female is $\frac{1}{2}$,

$$F_t \sim Bin\left(N_{t - \alpha}, \frac{\phi^\alpha}{2}\right),$$
and
$$E(F_t) = E(E(F_t|N_{t - \alpha}))$$
$$= E\left(N_{t - \alpha}\frac{\phi^\alpha}{2}\right)$$
$$= E(N_{t - \alpha})\frac{\phi^\alpha}{2}$$
$$= \frac{E(N_t)}{\lambda^\alpha}\frac{\phi^\alpha}{2},$$
from \@ref(eq:expNt),
\begin{equation}
  E(F_t) = \frac{E(N_t)}{2}\left(\frac{\phi}{\lambda}\right)^\alpha.
  (\#eq:expFt)
\end{equation}

Let

- $\beta$ be the probability that a given mature female gives birth to a calf at a given time.

Assume that

- a given female cannot give birth to more than one calf at a given time, and
- births occur independently of each other.

Then

$$B_t \sim Bin(F_t, \beta),$$
$$E(B_t) = E(E(B_t|F_t))$$
$$= E(F_t \beta)$$
$$= E(F_t) \beta,$$
and
$$\beta = \frac{E(B_t)}{E(F_t)},$$
$$= \frac{E(N_{t - 1}) (\lambda - \phi)} {\frac{E(N_t)}{2}\left(\frac{\phi}{\lambda}\right)^\alpha},$$
from \@ref(eq:expBt) and \@ref(eq:expFt),
$$= 2 \frac{E(N_{t - 1}) (\lambda - \phi)} {E(N_t) }\left(\frac{\lambda}{\phi}\right)^\alpha$$
$$= 2 \frac{E(N_{t - 1}) (\lambda - \phi)} {E(N_{t - 1}) \lambda }\left(\frac{\lambda}{\phi}\right)^\alpha$$
\begin{equation}
  \beta = 2\left(1 - \frac{\phi}{\lambda} \right) \left(\frac{\lambda}{\phi}\right)^\alpha.
  (\#eq:beta)
\end{equation}

# Expected number of same-mother pairs within survey years

Let $b_1$, and $b_2$ be the years of birth of a pair of animals that are alive at time $t$.  New Zealand southern right whales have one calf at a time, so if the animals have the same mother then $b_1 \ne b_2$.  Let $b_1$ be the birth year of the older sibling, so that $b_1 < b_2$.

For each animal born at time $b_1$ the probability that it survives to time $t$ is $\phi^{t - b_1}$.

The probability that the mother survives from time $b_1$ to time $b_2$ is $\phi^{b_2 - b_1}$.

The probability that the mother has another calf at time $b_2$, given that she survives until then, is $\beta$.

The probability that this calf survives to time $t$ is $\phi^{t - b_2}$.

For each animal born at time $b_1$ the probability that there is an animal born at time $b_2$ with the same mother, and that they both survive to time $t$ is then $\phi^{t - b_1}\phi^{b_2 - b_1}\beta\phi^{t - b_2} = \phi^{2(t - b_1)}\beta$.

Let $SMP_{t, b_1, b_2}$ be the number of pairs of animals at time $t$, with birth years $b_1$ and $b_2$, where $b_1 < b_2$, and the same mother.  

Then
$$SMP_{t, b_1, b_2} \sim Bin(B_{b_1}, \phi^{2(t - b_1)}\beta),$$
and
$$E(SMP_{t, b_1, b_2}) = E(E(SMP_{t, b_1, b_2}|B_{b_1}))$$
$$= E(B_{b_1}\phi^{2(t - b_1)}\beta)$$
$$= E(B_{b_1})\phi^{2(t - b_1)}\beta$$
$$= E(N_{b_1})\left(1 - \frac{\phi}{\lambda}\right)\phi^{2(t - b_1)}\beta$$
$$= \frac{E(N_t)}{\lambda^{t - b_1}}\left(1 - \frac{\phi}{\lambda}\right)\phi^{2(t - b_1)}\beta$$
$$= E(N_t)\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}\beta$$
$$= E(N_t)\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}2\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\lambda}{\phi}\right)^\alpha$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}.$$

Let $SMP_t$ be the number of pairs of animals at time $t$ with the same mother and any birth years.

Then
$$SMP_t = \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}SMP_{t, b_1, b_2},$$
$$E(SMP_t) = \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}E(SMP_{t, b_1, b_2}),$$
$$= \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\sum_{b_1 < t}\sum_{b_1 < b_2 \le t}\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\sum_{b_1 < t}(t - b_1)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left\{\frac{\phi^2}{\lambda} + 2\left(\frac{\phi^2}{\lambda}\right)^2 + 3\left(\frac{\phi^2}{\lambda}\right)^3 + ...\right\},$$
$$r + 2r^2 + 3r^3 + ... = \frac{1 - r}{1 - r}(r + 2r^2 + 3r^3 + ...)$$
$$= \frac{1}{1 - r}(r + 2r^2 + 3r^3 + ... - r^2 - 2r^3 - 3r^4 - ...)$$
$$= \frac{1}{1 - r}(r + r^2 + r^3 + ...),$$
for $|r| < 1$,
$$= \frac{1}{1 - r}\frac{1 - r}{1 - r}(r + r^2 + r^3 + ...)$$
$$= \frac{1}{1 - r}\frac{1}{1 - r}(r + r^2 + r^3 + ... - r^2 - r^3 - r^4 - ...)$$
$$= \frac{1}{1 - r}\frac{1}{1 - r}r,$$
for $|r| < 1$,
$$= \frac{r}{(1 - r)^2},$$
and
$$E(SMP_t) = 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left\{\frac{\phi^2}{\lambda} + 2\left(\frac{\phi^2}{\lambda}\right)^2 + 3\left(\frac{\phi^2}{\lambda}\right)^3 + ...\right\}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\frac{\frac{\phi^2}{\lambda}}{\left( 1 - \frac{\phi^2}{\lambda} \right)^2}$$
because 
$$0 \le S_t \le N_{t + 1},$$
$$0 \le E(S_t) \le E(N_{t + 1}),$$
$$0 \le E(N_t) \phi \le E(N_t) \lambda,$$
from \@ref(eq:expNt) and \@ref(eq:expSt), and
\begin{equation}
  0 \le \phi \le \lambda,
  (\#eq:philambda)
\end{equation}
$$0 < \frac{\phi}{\lambda} < 1,$$
and
$$0 < \frac{\phi^2}{\lambda} < 1,$$
as $0 < \phi < 1$,
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\frac{\lambda\phi^2}{\left(\lambda - \phi^2\right)^2}.$$

# Expected number of same-mother pairs between survey years

Let $i$ and $j$ be a pair of animals, where 

- $i$ is alive at time $t_1$, and $j$ is alive at time $t_2$, where $t_1 < t_2$,
- $i$ has birth year $b_1$, and $j$ has birth year $b_2$, where $b_1 < b_2$, and 
- $i$ and $j$ have the same mother.

The probability that $i$ survives to time $t_1$ is $\phi^{t_1 - b_1}$.

The probability that the mother survives from time $b_1$ to time $b_2$ is $\phi^{b_2 - b_1}$.

The probability that the mother has another calf at time $b_2$, given that she survives until then, is $\beta$.

If $b_2 < t_1$ the probability that this calf survives to time $t_1$ is $\phi^{t_1 - b_2}$.  Then if either $i$ or $j$ survives to time $t_2$

The probability that this calf survives to time $t_2$ is $\phi^{t_2 - b_2}$.

For each animal born at time $b_1$ the probability that it forms a pair such as $i$ and $j$ is then $\phi^{t_1 - b_1}\phi^{b_2 - b_1}\beta\phi^{t_2 - b_2} = \phi^{2(t_1 - b_1) + t_2 - t_1}\beta$.

Let $SMP_{t_1, t_2, b_1, b_2}$ be the number of pairs such as $i$ and $j$.  Then
$$SMP_{t_1, t_2, b_1, b_2} \sim Bin(B_{b_1}, \phi^{2(t_1 - b_1) + t_2 - t_1}\beta),$$
and following the same reasoning as above
$$E(SMP_{t_1, t_2, b_1, b_2}) = E(B_{b_1})\phi^{2(t_1 - b_1) + t_2 - t_1}\beta$$
$$= E(SMP_{t_1, b_1, b_2}) \phi^{t_2 - t_1}.$$
Let $SMP_{t_1, t_2}$ be the number of pairs of animals such as $i$ and $j$, but with any birth years.

Then
$$SMP_{t_1, t_2} = \sum_{b_1 \le t_1}\sum_{b_1 < b_2 \le t_2}SMP_{t_1, t_2, b_1, b_2},$$
$$E(SMP_{t_1, t_2}) = \sum_{b_1 \le t_1}\sum_{b_1 < b_2 \le t_2}E(SMP_{t_1, t_2, b_1, b_2})$$
$$= \sum_{b_1 \le t_1} \left\{\sum_{b_1 < b_2 \le t_1} 2 E(SMP_{t_1, b_1, b_2}) \phi^{t_2 - t_1} + \sum_{t_1 < b_2 \le t_2} E(SMP_{t_1, b_1, b_2}) \phi^{t_2 - t_1}\right\}$$
$$= \sum_{b_1 \le t_1} \sum_{b_1 < b_2 \le t_1} 2 \left\{2E(N_{t_1})\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left(\frac{\phi^2}{\lambda}\right)^{t_1 - b_1}\right\} \phi^{t_2 - t_1} +$$
$$\sum_{b_1 \le t_1} \sum_{t_1 < b_2 \le t_2} 2E(N_{t_1})\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left(\frac{\phi^2}{\lambda}\right)^{t_1 - b_1}  \phi^{t_2 - t_1}$$
$$= 2 E(N_{t_1}) \left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \phi^{t_2 - t_1} \sum_{b_1 \le t_1} \left(\frac{\phi^2}{\lambda}\right)^{t_1 - b_1} \left\{\sum_{b_1 < b_2 \le t_1} 2 + \sum_{t_1 < b_2 \le t_2} 1\right\}$$
$$\sum_{b_1 \le t_1} \left(\frac{\phi^2}{\lambda}\right)^{t_1 - b_1} \left\{\sum_{b_1 < b_2 \le t_1} 2 + \sum_{t_1 < b_2 \le t_2} 1\right\} = \sum_{b_1 \le t_1} \left(\frac{\phi^2}{\lambda}\right)^{t_1 - b_1} \{2(t_1 - b_1) + t_2 - t_1\}$$
$$= t_2 - t_1 + \frac{\phi^2}{\lambda} (2 + t_2 - t_1) + \left(\frac{\phi^2}{\lambda}\right)^2 (4 + t_2 - t_1) + ...$$
$$= (t_2 - t_1) \left\{1 + \frac{\phi^2}{\lambda} + \left(\frac{\phi^2}{\lambda}\right)^2 + ... \right\} + 2 \frac{\phi^2}{\lambda} \left\{1 + 2\frac{\phi^2}{\lambda} + 3\left(\frac{\phi^2}{\lambda}\right)^2 + ... \right\}$$
$$= (t_2 - t_1) \frac{1}{1 - \frac{\phi^2}{\lambda}} + 2 \frac{\phi^2}{\lambda} \frac{1}{\left(1 - \frac{\phi^2}{\lambda}\right)^2}$$
$$= (t_2 - t_1) \frac{\lambda}{\lambda - \phi^2} + 2 \frac{\phi^2}{\lambda} \frac{\lambda^2}{\left(\lambda - \phi^2\right)^2}$$
$$= \frac{\lambda}{\lambda - \phi^2} \left(t_2 - t_1 + \frac{2 \phi^2}{\lambda - \phi^2}\right)$$
$$E(SMP_{t_1, t_2}) = 2 E(N_{t_1}) \left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \phi^{t_2 - t_1} \frac{\lambda}{\lambda - \phi^2} \left(t_2 - t_1 + \frac{2\phi^2}{\lambda - \phi^2} \right)$$
$$= 2 E(N_{t_1}) \left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \phi^{t_2 - t_1} \frac{\lambda \phi^2}{(\lambda - \phi^2)^2} \left\{\frac{\lambda - \phi^2}{\phi^2}(t_2 - t_1) + 2 \right\}$$
$$= E(SMP_{t_1}) \phi^{t_2 - t_1} \left\{\frac{\lambda - \phi^2}{\phi^2}(t_2 - t_1) + 2 \right\}$$
