---
title: "Expected number of same-father pairs"
author: "Robin Aldridge-Sutton"
date: "05/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Expected number of same-father pairs within survey years, with different birth years

Male NZSRWs can breed with more than one female and have more than one offspring per year.  

Let 

- $M_t$ be the number of males at time $t$, that would be mature at time $t + 1$,
- $SFP_{t, b_1, b_2, i}$ be the number of pairs of animals at time $t$, that include a particular animal $i$, that is born at time $b_1$, and an animal born at a later time $b_2$, that has the same father, and 
- $SFP_{t, b_1, b_2}$ be the total number of pairs at time $t$ that include any animal born at time $b_1$, and an animal born at a later time $b_2$, that has the same father.

Assume that 

- there is always at least one mature male (this is a slight contradiction of our model so far, but that should only be significant when there is a significant chance of a population going extinct, in fact it is implied by the assumption of a constant birthrate for females, which requires that there is always at least one male to breed with),
- mature males at time $t - 1$ are equally likely to be the father of any calf born at time $t$, and 
- those events are independent.

Then the probability that an animal born at time $b_1$ survives to time $t$ is $\phi^{t - b_1}$, the probability that the father survives from time $b_1 - 1$ to time $b_2 - 1$ is $\phi^{b_2 - 1 - (b_1 - 1)} = \phi^{b_2 - b_1}$, the probability that a calf born at time $b_2$ has that father is $\frac{1}{M_{b_2 - 1}}$, and the probability that it also survives to time $t$ is $\phi^{t - b_2}$. So for any animal born at time $b_1$, the probability that an animal born at time $b_2$ forms a same-father pair with it at time $t$ is $\frac{\phi^{2(t - b_1)}}{M_{b_2 - 1}}$.  Then
$$SFP_{t, b_1, b_2, i} \sim Bin\left(B_{b_2}, \frac{\phi^{2(t - b_1)}}{M_{b_2 - 1}}\right),$$
$$SFP_{t, b_1, b_2} = \sum_{i = 1}^{B_{b_1}}SFP_{t, b_1, b_2, i},$$
and
$$E(SFP_{t, b_1, b_2}) = E\left(\sum_{i = 1}^{B_{b_1}}SFP_{t, b_1, b_2, i}\right)$$
$$= E\left\{E\left(\sum_{i = 1}^{B_{b_1}}SFP_{t, b_1, b_2, i}\Big|B_{b_1} \right) \right\}$$
$$= E\left\{\sum_{i = 1}^{B_{b_1}}E(SFP_{t, b_1, b_2, i})\right\}$$
$$= E\left\{B_{b_1}E(SFP_{t, b_1, b_2, i})\right\}$$
$$= E(B_{b_1})E(SFP_{t, b_1, b_2, i})$$
$$= E(B_{b_1})E\left\{E(SFP_{t, b_1, b_2, i}|B_{b_2}, M_{b_2 - 1})\right\}$$
$$= E(B_{b_1})E\left\{B_{b_2} \frac{\phi^{2(t - b_1)}}{M_{b_2 - 1}}\right\}$$
$$= E(B_{b_1})E\left\{ \frac{B_{b_2}}{M_{b_2 - 1}}\right\} \phi^{2(t - b_1)}$$
$$\approx E(B_{b_1})E(B_{b_2}) E\left(\frac{1}{M_{b_2 - 1}}\right) \phi^{2(t - b_1)},$$
as $B_{b_2}$ and $M_{b_2 - 1}$ are not independent but both depend on $N_{b_2 - 1 - \alpha}$,
$$= E(B_{b_1})E(B_{b_2}) \frac{1}{E(M_{b_2 - 1})} \phi^{2(t - b_1)}$$
$$= E(B_{b_1})E(B_{b_2}) \frac{1}{\frac{E(N_{b_2 - 1})}{2} \left(\frac{\phi}{\lambda}\right)^{\alpha - 1}} \phi^{2(t - b_1)}$$
$$= E(B_{b_1})E(B_{b_2}) \frac{2}{E(N_{b_2 - 1})} \left(\frac{\lambda}{\phi}\right)^{\alpha - 1} \phi^{2(t - b_1)}$$
$$= E(B_{b_1})E(B_{b_2}) \frac{2 \lambda}{E(N_{b_2})} \left(\frac{\lambda}{\phi}\right)^{\alpha - 1} \phi^{2(t - b_1)}$$
$$= E(B_{b_1})E(B_{b_2}) \frac{2 \phi}{E(N_{b_2})} \left(\frac{\lambda}{\phi}\right)^{\alpha} \phi^{2(t - b_1)}$$
$$= E(B_{b_1})E(B_{b_2}) \phi \frac{1}{E(F_{b_2})} \phi^{2(t - b_1)}$$
$$= E(B_{b_1}) \beta \phi^{2(t - b_1) + 1}$$
$$= E(SMP_{t, b_1, b_2}) \phi.$$

### Expected number of same-father pairs between survey years, with different birth years

Let $SFP_{t_1, t_2, b_1, b_2, i}$ be the number of pairs of animals $i$ and $j$, where 
- $i$ is alive at time $t_1$, $j$ is alive at time $t_2$$, and $t_1 < t_2$,
- $i$ is born at time $b_1$, and $j$ is born at a later time $b_2$, and
- $i$ and $j$ have the same father.
Then the probability that $i$ survives to time $t$ is $\phi^{t_1 - b_1}$, the probability that the father survives from time $b_1 - 1$ to time $b_2 - 1$ is $\phi^{b_2 - 1 - (b_1 - 1)} = \phi^{b_2 - b_1}$, the probability that $j$ has that father is $\frac{1}{M_{b_2 - 1}}$, and the probability that it survives to time $t_2$ is $\phi^{t_2 - b_2}$. So for any animal born at time $b_1$, the probability that an animal born at time $b_2$ forms a same-father pair with it at time $t$ is $\frac{\phi^{2(t_1 - b_1) + t_2 - t_1}}{M_{b_2 - 1}}$.  Then
$$SFP_{t_1, t_2, b_1, b_2, i} \sim Bin\left(B_{b_2}, \frac{\phi^{2(t - b_1) + t_2 - t_1}}{M_{b_2 - 1}}\right),$$
and following the same reasoning as above,
$$E(SFP_{t_1, t_2, b_1, b_2, i}) = E(B_{b_1})E\left\{B_{b_2} \frac{\phi^{2(t_1 - b_1) + t_2 - t_1}}{M_{b_2 - 1}}\right\}$$
$$= E(B_{b_1})E\left\{B_{b_2} \frac{\phi^{2(t_1 - b_1)}}{M_{b_2 - 1}}\right\} \phi^{t_2 - t_1}$$
$$= E(SFP_{t_1, b_1, b_2}) \phi^{t_2 - t_1}$$

### Expected number of same-father pairs within survey years, with the same birth year

Let 

- $SFB_{t, b, f}$ be the number of animals at time $t$, that are born at time $b$, with a particular father $f$, 
- $SFP_{t, b, f}$ be the number of pairs of animals at time $t$, that are both born at time $b$, with a particular father $f$, and 
- $SFP_{t, b}$ be the total number of pairs of animals at time $t$, that are both born at time $b$, and have the same father.

Then the probability that an animal born at time $b$ has a particular father $f$ is $\frac{1}{M_{b - 1}}$, the probability that it also survives to time $t$ is $\frac{\phi^{t - b}}{M_{b - 1}}$, and
$$SFB_{t, b, f} \sim Bin\left(B_b, \frac{\phi^{t - b}}{M_{b - 1}}\right),$$
$$SFP_{t, b, f} = {SFB_{t, b, f} \choose 2},$$
$$SFP_{t, b} = \sum_{f = 1}^{M_{b - 1}}SFP_{t, b, f},$$
and
$$E(SFP_{t, b}) = E\left(\sum_{f = 1}^{M_{b - 1}}SFP_{t, b, f}\right)$$
$$= E\left\{E\left(\sum_{f = 1}^{M_{b - 1}}SFP_{t, b, f}\Big|M_{b - 1} \right) \right\}$$
$$= E\left\{\sum_{f = 1}^{M_{b - 1}}E(SFP_{t, b, f})\right\}$$
$$= E\left\{M_{b - 1}E(SFP_{t, b, f})\right\}$$
$$= E(M_{b - 1})E(SFP_{t, b, f})$$
$$= E(M_{b - 1})E\left\{{SFB_{t, b, f} \choose 2}\right\}$$
$$= E(M_{b - 1})E\left[E\left\{{SFB_{t, b, f} \choose 2}\Big|B_b, M_{b - 1}\right\}\right].$$
When $X \sim Bin(n, p)$,
$$E\left\{{X \choose 2}\right\} = \sum_{x = 0}^n {n \choose x}p^x (1 - p)^{n - x}{x \choose 2}$$
$$= \sum_{x = 0}^n \frac{n!}{x!(n - x)!}p^x (1 - p)^{n - x}\frac{x!}{2!(x - 2)!}$$
$$= \sum_{x = 0}^n \frac{n!}{x!(n - x)!}p^x (1 - p)^{n - x}\frac{x(x - 1)}{2}$$
$$= \sum_{x = 2}^n \frac{n!}{x!(n - x)!}p^x (1 - p)^{n - x}\frac{x(x - 1)}{2}$$
$$= \frac{1}{2} \sum_{x = 2}^n \frac{n!}{(x - 2)!(n - x)!}p^x (1 - p)^{n - x}$$
$$= \frac{n(n - 1)p^2}{2} \sum_{x = 2}^n \frac{(n - 2)!}{(x - 2)!(n - x)!}p^{x - 2} (1 - p)^{n - x}$$
$$= \frac{n(n - 1)p^2}{2} \sum_{x = 0}^{n - 2} \frac{(n - 2)!}{x!(n - (x + 2))!}p^x (1 - p)^{n - (x + 2)}$$
$$= \frac{n(n - 1)p^2}{2} \sum_{x = 0}^{n - 2} \frac{(n - 2)!}{x!(n - 2 - x)!}p^x (1 - p)^{n - 2 - x}$$
$$= \frac{n(n - 1)p^2}{2}$$
$$= {n \choose 2} p^2.$$
So
$$E(SFP_{t, b}) = E(M_{b - 1})E\left[E\left\{{SFB_{t, b, f} \choose 2}\Big|B_b, M_{b - 1}\right\}\right]$$
$$= E(M_{b - 1})E\left\{{B_b \choose 2}\left(\frac{\phi^{t - b}}{M_{b - 1}}\right)^2\right\}$$
$$\approx E(M_{b - 1})E\left\{{B_b \choose 2}\right\}E\left\{\left(\frac{1}{M_{b - 1}}\right)^2\right\}\phi^{2(t - b)},$$
the approximation obtained by treating $B_b$ and $M_{b - 1}$ as independent although they are both dependent on $N_{b - 1 - \alpha}$, and remembering that we assume $M_{b - 1} \ge 1$,
$$\approx E(M_{b - 1})E\left\{{B_b \choose 2}\right\}\left\{E\left(\frac{1}{M_{b - 1}}\right)\right\}^2\phi^{2(t - b)},$$
$$\approx E(M_{b - 1})E\left\{{B_b \choose 2}\right\}\left\{\frac{1}{E(M_{b - 1})}\right\}^2\phi^{2(t - b)},$$
the two approximations being more accurate as $E(M_{b - 1}) \rightarrow \infty$ so that the derivatives of $\left(\frac{1}{M_{b - 1}}\right)^2$ and $\frac{1}{M_{b - 1}}$ approach zero for the most likely values of $M_{b - 1}$, so that they are close to linear (constant) functions of $M_{b - 1}$.  Then
$$E(SFP_{t, b}) \approx E\left\{{B_b \choose 2}\right\}\frac{\phi^{2(t - b)}}{E(M_{b - 1})}$$
$$= E\left[E\left\{{B_b \choose 2}\Big|F_b\right\}\right]\frac{\phi^{2(t - b)}}{E(M_{b - 1})}$$
$$= E\left\{{F_b \choose 2}\beta^2\right\}\frac{\phi^{2(t - b)}}{E(M_{b - 1})}$$
$$= E\left[E\left\{{F_b \choose 2}\Big|N_{b - \alpha}\right\}\right]\frac{\beta^2 \phi^{2(t - b)}}{E(M_{b - 1})}$$
$$= E\left\{{N_{b - \alpha} \choose 2}\left(\frac{\phi^\alpha}{2}\right)^2 \right\}\frac{\beta^2 \phi^{2(t - b)}}{E(M_{b - 1})}$$
$$= E\left\{{N_{b - \alpha} \choose 2} \right\}\frac{\beta^2 \phi^{2 (t - b + \alpha)}}{4 E(M_{b - 1})}$$
$$= E\left\{\frac{N_{b - \alpha}(N_{b - \alpha} - 1)}{2} \right\}\frac{\beta^2 \phi^{2 (t - b + \alpha)}}{4 E(M_{b - 1})}$$
$$\approx \frac{E(N_{b - \alpha})E(N_{b - \alpha} - 1)}{2} \frac{\beta^2 \phi^{2 (t - b + \alpha)}}{4 E(M_{b - 1})}$$
$$= \frac{E(N_t)}{\lambda^{t - b + \alpha}} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \frac{\beta^2 \phi^{2 (t - b + \alpha)}}{8 E(M_{b - 1})}$$
$$= \frac{E(N_t)}{\lambda^{t - b + \alpha}} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left\{ 2 \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \frac{\phi^{2 (t - b + \alpha)}}{8 \frac{E(N_{b - 1})}{2} \left( \frac{\phi}{\lambda} \right)^\alpha}$$
$$= \frac{E(N_t)}{\lambda^{t - b + \alpha}} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left\{ 2 \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \frac{\phi^{2 (t - b + \alpha)}}{8 } \frac{2}{E(N_{b - 1})} \left( \frac{\lambda}{\phi} \right)^\alpha$$
$$= \frac{E(N_t)}{\lambda^{t - b + \alpha}} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left\{ \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{2 (t - b + \alpha)} \frac{1}{E(N_{b - 1})} \left( \frac{\lambda}{\phi} \right)^\alpha$$
$$= \frac{E(N_t)}{\lambda^{t - b + \alpha}} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left\{ \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{2 (t - b + \alpha)} \frac{\lambda^{t - b + 1}}{E(N_t)} \left( \frac{\lambda}{\phi} \right)^\alpha$$
$$= \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left\{ \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{2 (t - b + \alpha)} \lambda \left( \frac{1}{\phi} \right)^\alpha$$
$$= \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left(1 - \frac{\phi}{\lambda} \right)^2  \left( \frac{\lambda}{\phi}\right)^{2 \alpha} \phi^{2 (t - b + \alpha)} \lambda \left( \frac{1}{\phi} \right)^\alpha$$
$$= \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left(1 - \frac{\phi}{\lambda} \right)^2  \left( \frac{\lambda^2}{\phi}\right)^{\alpha} \phi^{2 (t - b)} \lambda.$$

### Expected number of same-father pairs

Let $SFP_t$ be the total number of pairs of animals at time $t$ with the same father.  Then
$$SFP_t = \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}SFP_{t, b_1, b_2} + \sum_{b \le t} SFP_{t, b}$$
$$E(SFP_t) = E\left(\sum_{b_1 < t}\sum_{b_1 < b_2 \le t}SFP_{t, b_1, b_2} + \sum_{b \le t} SFP_{t, b}\right)$$
$$= \sum_{b_1 < t}\sum_{b_1 < b_2 \le t} E(SFP_{t, b_1, b_2}) + \sum_{b \le t} E(SFP_{t, b})$$
$$= \sum_{b_1 < t}\sum_{b_1 < b_2 \le t} E(SMP_{t, b_1, b_2}) \phi + \sum_{b \le t} E(SFP_{t, b})$$
$$= \phi \sum_{b_1 < t}\sum_{b_1 < b_2 \le t} E(SMP_{t, b_1, b_2}) + \sum_{b \le t} E(SFP_{t, b})$$
$$= \phi E(SMP_t) + \sum_{b \le t} E(SFP_{t, b}),$$
$$\sum_{b \le t} E(SFP_{t, b}) = \sum_{b \le t} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\} \left(1 - \frac{\phi}{\lambda} \right)^2  \left( \frac{\lambda^2}{\phi}\right)^{\alpha} \phi^{2 (t - b)} \lambda$$
$$= \left(1 - \frac{\phi}{\lambda} \right)^2 \left( \frac{\lambda^2}{\phi}\right)^{\alpha} \lambda \sum_{b \le t} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\}   \phi^{2 (t - b)},$$
$$\sum_{b \le t} \left\{ \frac{E(N_t)}{\lambda^{t - b + \alpha}} - 1 \right\}   \phi^{2 (t - b)} = \sum_{b \le t} \left\{ \frac{E(N_t)}{\lambda^{\alpha}} \left(\frac{\phi^2}{\lambda}\right)^{t - b} - \phi^{2 (t - b)} \right\}$$
$$= \sum_{b \le t} \frac{E(N_t)}{\lambda^{\alpha}} \left(\frac{\phi^2}{\lambda}\right)^{t - b} - \sum_{b \le t} \phi^{2 (t - b)} $$
$$= \frac{E(N_t)}{\lambda^{\alpha}} \sum_{b \le t}  \left(\frac{\phi^2}{\lambda}\right)^{t - b} - \sum_{b \le t} \phi^{2 (t - b)} $$
$$= \frac{E(N_t)}{\lambda^{\alpha}} \left\{1 + \frac{\phi^2}{\lambda} + \left(\frac{\phi^2}{\lambda}\right)^2 + ... \right\} - (1 + \phi^2 + \phi^4 + ...) $$
$$= \frac{E(N_t)}{\lambda^{\alpha}} \frac{1}{1 - \frac{\phi^2}{\lambda}} - \frac{1}{1 - \phi^2} $$
$$= \frac{E(N_t)}{\lambda^{\alpha}} \frac{\lambda}{\lambda - \phi^2} - \frac{1}{1 - \phi^2} $$
$$\sum_{b \le t} E(SFP_{t, b}) = \left(1 - \frac{\phi}{\lambda} \right)^2 \left( \frac{\lambda^2}{\phi}\right)^{\alpha} \lambda \left\{\frac{E(N_t)}{\lambda^{\alpha}} \frac{\lambda}{\lambda - \phi^2} - \frac{1}{1 - \phi^2}\right\}$$
$$E(SFP_t) = \phi E(SMP_t) + \sum_{b \le t} E(SFP_{t, b})$$
$$ = \phi 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \frac{\lambda\phi^2}{\left(\lambda - \phi^2\right)^2} +$$
$$\left(1 - \frac{\phi}{\lambda} \right)^2 \left( \frac{\lambda^2}{\phi}\right)^{\alpha} \lambda \left\{\frac{E(N_t)}{\lambda^{\alpha}} \frac{\lambda}{\lambda - \phi^2} - \frac{1}{1 - \phi^2} \right\}$$
$$= \left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \lambda \left[ \frac{2E(N_t)\phi^3}{\left(\lambda - \phi^2\right)^2} + \lambda^\alpha \left\{\frac{E(N_t)}{\lambda^{\alpha}} \frac{\lambda}{\lambda - \phi^2} - \frac{1}{1 - \phi^2} \right\} \right] $$
$$= \left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \lambda \left\{ \frac{2E(N_t)\phi^3}{\left(\lambda - \phi^2\right)^2} + \frac{E(N_t)\lambda}{\lambda - \phi^2} - \frac{\lambda^\alpha}{1 - \phi^2} \right\} $$
$$= \left(1 - \frac{\phi}{\lambda}\right)^2 \left(\frac{\lambda}{\phi}\right)^\alpha \lambda \left\{ \frac{E(N_t)}{\lambda - \phi^2} \left( \frac{2\phi^3}{\lambda - \phi^2} + \lambda \right) - \frac{\lambda^\alpha}{1 - \phi^2} \right\} $$