---
title: "Half-sibling pair probability for New Zealand southern right whales"
author: "Robin Aldridge-Sutton"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Expected number of animals born at time $t$

Let 

- $N_t$ be the population size at time $t$, 
- $\phi$ be the probability of an animal surviving from time $t - 1$ to time $t$, and 
- $\lambda = \frac {E(N_{t})}{E(N_{t - 1})}$ be the population growth rate, where $E(.)$ is the expected value of $.$, and $\lambda \ge \phi$.

Then
$$E(N_{t - 1}) = \frac{E(N_t)}{\lambda},$$
$$E(N_{t - 2}) = \frac{E(N_{t - 1})}{\lambda} = \frac{E(N_t)}{\lambda^2},$$
and
$$E(N_{t_1}) = \frac{E(N_{t_2})}{\lambda^{t_2 - t_1}}.$$

The probability that an animal survives from time $t_1$ to time $t_2$ is $\phi^{t_2 - t_1}$, where $t_2 > t_1$.

Let $S$ be the number of animals that survive from time $t - 1$ to time $t$. 

Then 
$$S \sim Bin(N_{t - 1}, \phi),$$
and
$$E(S) = E\{E(S|N_{t - 1})\}$$
$$= E(N_{t - 1} \phi)$$
$$= E(N_{t - 1}) \phi$$
$$= \frac{E(N_t)}{\lambda}\phi$$
$$= E(N_t)\frac{\phi}{\lambda}.$$

Let $B_t$ be the number of animals that are born at time $t$.  

Then
$$B_t = N_t - S,$$
and
$$E(B_t) = E(N_t - S)$$
$$= E(N_t) - E(S)$$
$$= E(N_t) - E(N_t) \frac{\phi}{\lambda}$$
$$= E(N_t) \left(1 - \frac{\phi}{\lambda} \right).$$

### Birth rate among mature females

Let 

- $\alpha$ be the age of sexual maturity for NZSRWs, and
- $F_t$ be the number of mature females at time $t$,

and assume that

- births occur independently with probability (birth rate) $\beta$ among mature females, and
- animals are equally likely to be born male or female.

Then the probability that an animal is mature at time $t$ (has survived since at least time $t - \alpha$) is $\phi^\alpha$, the probability that an animal is female is $\frac{1}{2}$, and

$$F_t \sim Bin\left(N_{t - \alpha}, \frac{\phi^\alpha}{2}\right),$$
$$E(F_t) = E(E(F_t|N_{t - \alpha}))$$
$$= E\left(N_{t - \alpha}\frac{\phi^\alpha}{2}\right)$$
$$= E(N_{t - \alpha})\frac{\phi^\alpha}{2}$$
$$= \frac{E(N_t)}{\lambda^\alpha}\frac{\phi^\alpha}{2}$$
$$= \frac{E(N_t)}{2}\left(\frac{\phi}{\lambda}\right)^\alpha,$$
$$B_t \sim Bin(F_t, \beta),$$
$$E(B_t) = E(E(B_t|F_t))$$
$$= E(F_t \beta)$$
$$= E(F_t) \beta,$$
and
$$\beta = \frac{E(B_t)}{E(F_t)},$$
$$= \frac{E(N_t) \left(1 - \frac{\phi}{\lambda} \right)}{\frac{E(N_t)}{2}\left(\frac{\phi}{\lambda}\right)^\alpha}$$
$$= \frac{\left(1 - \frac{\phi}{\lambda} \right)}{\frac{1}{2}\left(\frac{\phi}{\lambda}\right)^\alpha}$$
$$= 2\left(1 - \frac{\phi}{\lambda} \right)\left(\frac{\lambda}{\phi}\right)^\alpha.$$

### Expected number of same-mother pairs

Let $b_1$, and $b_2$ be the years of birth of a pair of animals that are alive at time $t$.  New Zealand southern right whales have one calf at a time, so if the animals have the same mother then $b_1 \ne b_2$.  Let $b_1$ be the birth year of the older sibling, so that $b_1 < b_2$.

For each animal born at time $b_1$ the probability that it survives to time $t$ is $\phi^{t - b_1}$.

The probability that the mother survives from time $b_1$ to time $b_2$ is $\phi^{b_2 - b_1}$.

The probability that the mother has another calf at time $b_2$, given that she survives until then, is $\beta$.

The probability that this calf survives to time $t$ is $\phi^{t - b_2}$.

For each animal born at time $b_1$ the probability that there is an animal born at time $b_2$ with the same mother, and that they both survive to time $t$ is then $\phi^{t - b_1}\phi^{b_2 - b_1}\beta\phi^{t - b_2} = \phi^{2(t - b_1)}\beta$.

Let $SMP_{t, b_1, b_2}$ be the number of pairs of animals at time $t$, with birth years $b_1$ and $b_2$, where $b_1 < b_2$, and the same mother.  

Then
$$SMP_{t, b_1, b_2} \sim Bin(B_{b_1}, \phi^{2(t - b_1)}\beta),$$
and
$$E(SMP_{t, b_1, b_2}) = E(E(SMP_{t, b_1, b_2}|B_{b_1}))$$
$$= E(B_{b_1}\phi^{2(t - b_1)}\beta)$$
$$= E(B_{b_1})\phi^{2(t - b_1)}\beta$$
$$= E(N_{b_1})\left(1 - \frac{\phi}{\lambda}\right)\phi^{2(t - b_1)}\beta$$
$$= \frac{E(N_t)}{\lambda^{t - b_1}}\left(1 - \frac{\phi}{\lambda}\right)\phi^{2(t - b_1)}\beta$$
$$= E(N_t)\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}\beta$$
$$= E(N_t)\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}2\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\lambda}{\phi}\right)^\alpha$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}.$$

Let $SMP_t$ be the number of pairs of animals at time $t$ with the same mother and any birth years.

Then
$$SMP_t = \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}SMP_{t, b_1, b_2},$$
$$E(SMP_t) = \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}E(SMP_{t, b_1, b_2}),$$
$$= \sum_{b_1 < t}\sum_{b_1 < b_2 \le t}2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\sum_{b_1 < t}\sum_{b_1 < b_2 \le t}\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\sum_{b_1 < t}(t - b_1)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left\{\frac{\phi^2}{\lambda} + 2\left(\frac{\phi^2}{\lambda}\right)^2 + 3\left(\frac{\phi^2}{\lambda}\right)^3 + ...\right\},$$
$$r + 2r^2 + 3r^3 + ... = \frac{1 - r}{1 - r}(r + 2r^2 + 3r^3 + ...)$$
$$= \frac{1}{1 - r}(r + 2r^2 + 3r^3 + ... - r^2 - 2r^3 - 3r^4 - ...)$$
$$= \frac{1}{1 - r}(r + r^2 + r^3 + ...),$$
for $|r| < 1$,
$$= \frac{1}{1 - r}\frac{1 - r}{1 - r}(r + r^2 + r^3 + ...)$$
$$= \frac{1}{1 - r}\frac{1}{1 - r}(r + r^2 + r^3 + ... - r^2 - r^3 - r^4 - ...)$$
$$= \frac{1}{1 - r}\frac{1}{1 - r}r,$$
for $|r| < 1$,
$$= \frac{r}{(1 - r)^2},$$
and
$$E(SMP_t) = 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\left\{\frac{\phi^2}{\lambda} + 2\left(\frac{\phi^2}{\lambda}\right)^2 + 3\left(\frac{\phi^2}{\lambda}\right)^3 + ...\right\}$$
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\frac{\frac{\phi^2}{\lambda}}{\left( 1 - \frac{\phi^2}{\lambda} \right)^2}$$
because $0 < \frac{\phi^2}{\lambda} < 1$,
$$= 2E(N_t)\left(1 - \frac{\phi}{\lambda}\right)^2\left(\frac{\lambda}{\phi}\right)^\alpha\frac{\lambda\phi^2}{\left(\lambda - \phi^2\right)^2}.$$

### Expected number of same-father pairs

Male NZSRWs can breed with more than one female and have more than one offspring per year.  

Let 

- $M_t$ be the number of mature males at time $t$,
- $SFB_{t, b, f}$ be the number of animals at time $t$, that are born at time $b$, with a particular father $f$, and 
- $SFP_{t, b, f}$ be the number of pairs of animals at time $t$, that are both born at time $b$, with a particular father $f$, and 
- $SFP_{t, b}$ be the total number of pairs of animals at time $t$, that are both born at time $b$, and have the same father,  

and assume that 

- mature males at time $t - 1$ are equally likely to be the father of any calf born at time $t$, and 
- those events are independent.

Then
$$SFB_{t, b, f} \sim Bin\left(B_b, \frac{\phi^{2(t - 1)}}{M_{b - 1}}\right),$$
and
$$SFP_{t, b, f} = {SFB_{t, b, f}\choose2}.$$
If we assume that

$$E(SFP_{t, b}) = E(E(SMP_{t, b_1, b_2}|B_{b_1}))$$
$$= E(B_{b_1}\phi^{2(t - b_1)}\beta)$$
$$= E(B_{b_1})\phi^{2(t - b_1)}\beta$$
$$= E(N_{b_1})\left(1 - \frac{\phi}{\lambda}\right)\phi^{2(t - b_1)}\beta$$
$$= \frac{E(N_t)}{\lambda^{t - b_1}}\left(1 - \frac{\phi}{\lambda}\right)\phi^{2(t - b_1)}\beta$$
$$= E(N_t)\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}\beta$$
$$= E(N_t)\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\phi^2}{\lambda}\right)^{t - b_1}2\left(1 - \frac{\phi}{\lambda}\right)\left(\frac{\lambda}{\phi}\right)^\alpha$$

**End of current work**

### Expected number of half-sibling pairs at time $t$

The same process as above gives the expected total number of pairs at time $t$ with the same father
$$ E(SFP_t) = \sum_{b_1 \le t} \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\phi}{\lambda} \right)^{t - b_1} E(N_t) \sum_{b_1 \le b_2 \le t} \phi^{b_2 - b_1} 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \phi^{t - b_2}. $$
Here we allow $b_1 = b_2$ since a male may breed multiple times in one breeding period.  We also include the probability, $\phi$ that the father survives from the time of conception of the first animal to the time of its birth.  The probability that the mother has a calf at time $b_2$ is replaced with the expected number of calves that the father has at $b_2$, which takes the same form if we ignore the small difference in the case when $b1 = b_2$. 

$$ E(SFP_t) = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \sum_{b_1 \le t} \left( \frac{\phi^2}{\lambda} \right)^{t - b_1} (t - b_1 + 1) $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \left( 1 + 2 \frac{\phi^2}{\lambda} + ... \right) $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \frac{1}{\left( 1 - \frac{\phi^2}{\lambda} \right)^2} $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \left( \frac{\lambda}{\lambda - \phi^2} \right)^2. $$

The expected total number of pairs at time $t$ with both the same mother, and the same father (full-sibling pairs), is
$$ E(FSP_t) = \sum_{b_1 < t} \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\phi}{\lambda} \right)^{t - b_1} E(N_t) \sum_{b_1 < b_2 \le t} \phi^{b_2 - b_1} \phi^{b_2 - b_1} \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \phi^{t - b_2} \right\}^2 $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{-1} \sum_{b_1 < t} \left( \frac{\phi}{\lambda} \right)^{t - b_1} \sum_{b_1 < b_2 \le t} \phi^{2 (t - b_1)} $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{-1} \sum_{b_1 < t} \left( \frac{\phi^3}{\lambda} \right)^{t - b_1} (t - b_1) $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{-1} \left\{ \frac{\phi^3}{\lambda} + 2 \left( \frac{\phi^3}{\lambda} \right)^2 + ... \right\} $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \phi^{-1} \frac{\frac{\phi^3}{\lambda}}{\left(1 - \frac{\phi^3}{\lambda} \right)^2} $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \frac{\phi^2 \lambda}{\left(\lambda - \phi^3 \right)^2}. $$

Excluding the full-sibling pairs from the pairs with the same mothers, and from those with the same fathers, leaves the half-sibling pairs,

$$ E(HSP_t) = E(SMP_t) + E(SFP_t) - 2 E(FSP_t) $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \frac{\phi \lambda}{(\lambda - \phi^2)^2} + \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \left( \frac{\lambda}{\lambda - \phi^2} \right)^2 $$
$$ - 2 \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \left\{ 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \right\}^2 \frac{\phi^2 \lambda}{\left(\lambda - \phi^3 \right)^2} $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \left\{ \frac{\phi \lambda}{(\lambda - \phi^2)^2} + \left( \frac{\lambda}{\lambda - \phi^2} \right)^2 - 4 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \frac{\phi^2 \lambda}{\left(\lambda - \phi^3 \right)^2} \right\} $$
$$ = \left(1 - \frac{\phi}{\lambda} \right) E(N_t) 2 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \left\{ \frac{\lambda (\phi + \lambda)}{(\lambda - \phi^2)^2} - 4 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \frac{\phi^2 \lambda}{\left(\lambda - \phi^3 \right)^2} \right\}. $$
Leaving the expression in this form makes it easier to remember the origin and understand the significance of the various terms.  The first factor represents the proportion of the population that is born at any time.  The second is the current expected population size.  The next three factors represent the expected number of offspring that a mature animal will conceive at any time.  The remaining terms are more complicated but include closed form expressions of geometric series representing the probability of the siblings surviving to the present, and the parents surviving between their conceptions/births, across all possible combinations of birthyears.  The difference between the terms in the braces represents that the pair share one parent but not both.

The half-sibling pair *probability* is then found by dividing the expected number of half-sibling pairs by the expected total number of pairs, which we approximate with
$$ \frac{E(N_t) \left\{E(N_t - 1) \right\}}{2}, $$
giving
$$ P(HSP_t) = \frac{4 (\lambda - \phi)}{E(N_t) - 1} \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\lambda}{\phi} \right)^\alpha \left\{ \frac{\lambda (\phi + \lambda)}{(\lambda - \phi^2)^2} - 4 (\lambda - \phi) \left( \frac{\lambda}{\phi} \right)^\alpha \frac{\phi^2 \lambda}{\left(\lambda - \phi^3 \right)^2} \right\}. $$

The same process leads to the probability for pairs between samples at times $t_1$ and $t_2$, where $t_1 < t_2$, by simply replacing $t$ with $t_1$ in the first sum, as the older sibling must be born before the first sample, and replacing $t$ with $t_2$ in the second sum, as the younger sibling can be born anytime before the second sample.  The sums may not simplify as nicely then though.  I haven't tried this yet.