---
title: "Parent-offspring pair between samples probability"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In a parent-offspring pair (POP) in which one animal is alive at time $t_1$ and the other is alive at a later time $t_2$, so that $t_2 > t_1$, the parent must be alive at time $t_1$.  If it is not yet born then neither is the offspring, so neither is alive at time $t_1$.  If it is already dead then it is not alive at either time $t_1$ or $t_2$.  

In any such pair either the offspring was alive at time $t_1$, or it was born at a time $t$ such that $t_1 < t \le t_2$.  If it is already dead by time $t_1$ then it is not alive at either time $t_1$ or $t_2$.  If it was born after time $t_2$ then it was not alive at either time $t_1$ or $t_2$. 

### Offspring alive at time of first sample

If the offspring was alive at time $t_1$, then the pair are both alive at time $t_1$.  Then there is a POP between time $t_1$ and a later time $t_2$ for each animal that survives to time $t_2$.  The probability of each animal surviving is $\phi^{t_2 - t_1}$, where $\phi$ is the probability that an animal survives from time $t$ to time $t + 1$.  So the expected number of POPs is
$$ E(PO_{t_1}) 2 \phi^{t_2 - t_1} = 2 E(N_{t_1}) \frac{\phi (\lambda - \phi)}{\lambda - \phi^2} 2 \phi^{t_2 - t_1} $$
$$ = 4 E(N_{t_2}) \frac{\phi (\lambda - \phi)}{\lambda - \phi^2} \left( \frac{\phi}{\lambda} \right)^{t_2 - t_1}, $$
where $E(PO_{t_1})$ is the expected number of POPs at time $t_1$ as derived on pages 38-39 of Dissertation.pdf.

### Offspring born between sample-times

If the offspring was born at a time $t$ such that $t_1 < t \le t_2$, then there is a POP for each of its parents that was alive at time $t_1$, if and only if the offspring survives to time $t_2$.

The expected number of animals born in any year $t$ is 
$$ E(B_t) = \left(1 - \frac{\phi}{\lambda} \right) E(N_t), $$
as explained in HSP-probability.pdf, where $N_t$ is the population at time $t$, and 
$$ \lambda = \frac{E(N_{t + 1})}{E(N_t)} $$

The probability that the offspring survives to time $t_2$ is $\phi^{t_2 - t}$.

Let $\alpha$ be the age of maturity for the species, the minimum age at which an animal may have a calf alive in the population.  If the offspring was born between time $t_1$ and time $t_1 + \alpha$, so that $t_1 < t \le \alpha$, then its parents must have been alive at time $t_1$ in order that they be mature the year the offspring is born.

If the offspring was born between time $t_1 + \alpha$ and time $t_2$, so that $t_1 + \alpha < t \le t_2$, then the probability that each of its parents were alive at time $t_1$ is given by the number of animals that survived from time $t_1$ to time $t$, divided by the total number of mature animals at time $t$, the number that survived from time $t - \alpha$ to time $t$.

The expected number of animals that were alive at time $t_1$, and survived until time $t$, is
$$ \left( \frac{\phi}{\lambda} \right)^{t - t_1} E(N_t) $$
The expected number of animals that are mature at time $t$ is the expected number that were alive at time $t - \alpha$, and survived until time $t$, that is
$$ \left( \frac{\phi}{\lambda} \right)^{t - (t + \alpha)} E(N_t) = \left( \frac{\phi}{\lambda} \right)^{\alpha} E(N_t) $$

For animals born at time $t$, where $t > t_1 + \alpha$, the probability that each of their parents was alive at time $t_1$ is thus 
$$ \frac{\left( \frac{\phi}{\lambda} \right)^{t - t_1} E(N_t)}{\left( \frac{\phi}{\lambda} \right)^{\alpha} E(N_t)} $$
$$ = \left( \frac{\phi}{\lambda} \right)^{t - (t_1 + \alpha)}. $$

So the expected number of POPs between times $t_1$ and $t_2$, in which the offspring was born at a time $t$ such that $t_1 < t \le t_2$, and survives to time $t_2$, is
$$\begin{cases}
  2 \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \phi^{t_2 - t}, & 
  t_1 < t \le \min\{t_1 + \alpha, t_2\}, \\
  2 \left(1 - \frac{\phi}{\lambda} \right) E(N_t) \phi^{t_2 - t} \left( \frac{\phi}{\lambda} \right)^{t - (t_1 + \alpha)}, & 
  \min\{t_1 + \alpha, t_2\} < t \le t_2,
\end{cases}$$
where the factor of two is due to the offspring having two parents,
$$= 
\begin{cases}
  2 \left(1 - \frac{\phi}{\lambda} \right) E(N_{t_2}) \left( \frac{\phi}{\lambda} \right)^{t_2 - t}, & 
  t_1 < t \le \min\{t_1 + \alpha, t_2\}, \\
  2 \left(1 - \frac{\phi}{\lambda} \right) E(N_{t_2}) \left( \frac{\phi}{\lambda} \right)^{t_2 - t} \left( \frac{\phi}{\lambda} \right)^{t - (t_1 + \alpha)}, & 
  \min\{t_1 + \alpha, t_2\} < t \le t_2,
\end{cases}$$
$$= 2 \left(1 - \frac{\phi}{\lambda} \right) E(N_{t_2}) \left( \frac{\phi}{\lambda} \right)^{t_2} \times 
\begin{cases}
  \left( \frac{\phi}{\lambda} \right)^{- t}, & 
  t_1 < t \le \min\{t_1 + \alpha, t_2\}, \\
  \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)}, & 
  \min\{t_1 + \alpha, t_2\} < t \le t_2.
\end{cases}$$

Summing over the possible years gives the expected total number of such pairs 
$$ \sum_{t_1 < t \le t_2} 2 \left(1 - \frac{\phi}{\lambda} \right) E(N_{t_2}) \left( \frac{\phi}{\lambda} \right)^{t_2} \times 
\begin{cases}
  \left( \frac{\phi}{\lambda} \right)^{- t}, & 
  t_1 < t \le \min\{t_1 + \alpha, t_2\}, \\
  \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)}, & 
  \min\{t_1 + \alpha, t_2\} < t \le t_2,
\end{cases}$$
$$ = 2 \left(1 - \frac{\phi}{\lambda} \right) E(N_{t_2}) \left( \frac{\phi}{\lambda} \right)^{t_2} \sum_{t_1 < t \le t_2} 
\begin{cases}
  \left( \frac{\phi}{\lambda} \right)^{- t}, & 
  t_1 < t \le \min\{t_1 + \alpha, t_2\}, \\
  \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)}, & 
  \min\{t_1 + \alpha, t_2\} < t \le t_2,
\end{cases}$$
$$ = 2 \left(1 - \frac{\phi}{\lambda} \right) E(N_{t_2}) \left( \frac{\phi}{\lambda} \right)^{t_2} \left\{ \sum_{t_1 < t \le \min\{t_1 + \alpha, t_2\}} \left( \frac{\phi}{\lambda} \right)^{- t} + \sum_{\min\{t_1 + \alpha, t_2\} < t \le t_2} \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)} \right\},$$
$$\sum_{t_1 < t \le \min\{t_1 + \alpha, t_2\}} \left( \frac{\phi}{\lambda} \right)^{-t} = \frac{\left( \frac{\phi}{\lambda} \right)^{-(t_1 + 1)} - \left( \frac{\phi}{\lambda} \right)^{-(\min\{t_1 + \alpha, t_2\} + 1)}} {1 - \left( \frac{\phi}{\lambda} \right)^{-1}},$$
$$\sum_{\min\{t_1 + \alpha, t_2\} < t \le t_2} \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)} = 
\begin{cases}
  \left\{ t_2 - (t_1 + \alpha) \right\} \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)}, & 
  t_1 + \alpha < t_2, \\
  0, & 
  t_1 + \alpha \ge t_2.
\end{cases}$$

Adding the expected number of POPs in which the offspring is alive at the time of the first sample gives the expected number of POPs between samples, as
$$ E(POP_{t_1, t_2}) = 4 E(N_{t_2}) \frac{\phi (\lambda - \phi)}{\lambda - \phi^2} \left( \frac{\phi}{\lambda} \right)^{t_2 - t_1} + 2 E(N_{t_2}) \left(1 - \frac{\phi}{\lambda} \right) \left( \frac{\phi}{\lambda} \right)^{t_2} \times$$
$$ \left[ \frac{\left( \frac{\phi}{\lambda} \right)^{-(t_1 + 1)} - \left( \frac{\phi}{\lambda} \right)^{-(\min\{t_1 + \alpha, t_2\} + 1)}} {1 - \left( \frac{\phi}{\lambda} \right)^{-1}} + 
\begin{cases}
  \left\{ t_2 - (t_1 + \alpha) \right\} \left( \frac{\phi}{\lambda} \right)^{t_2 - (t_1 + \alpha)}, & 
  t_1 + \alpha < t_2, \\
  0, & 
  t_1 + \alpha \ge t_2.
\end{cases} \right]. $$


